import React, {FormEvent, useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Area, AreaChart} from 'recharts';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
type Theme = 'light' | 'dark';

function App(){
  const [data,setData]=useState<any|null>(null);
  const [token,setToken]=useState<string>(()=>localStorage.getItem('swasthyanet-token')||'');
  const [user,setUser]=useState<any|null>(()=>JSON.parse(localStorage.getItem('swasthyanet-user')||'null'));
  const [loginUsername,setLoginUsername]=useState('state.official');
  const [loginPassword,setLoginPassword]=useState('State@2026');
  const [loginError,setLoginError]=useState('');
  const [selected,setSelected]=useState('phc-rajapur');
  const [detail,setDetail]=useState<any>(null);
  const [loading,setLoading]=useState(true);
  const [theme,setTheme]=useState<Theme>(() => (localStorage.getItem('swasthyanet-theme') as Theme) || 'light');
  const [query,setQuery]=useState('');
  const [status,setStatus]=useState('all');
  const [alertFilter,setAlertFilter]=useState('all');
  const [autoRefresh,setAutoRefresh]=useState(true);
  const [toast,setToast]=useState('');

  const authFetch=(url:string,options:RequestInit={})=>fetch(url,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${token}`}});
  const load=()=>authFetch(`${API}/api/dashboard`).then(async r=>{if(r.status===401){logout();throw new Error('session')}return r.json()}).then(setData).catch(()=>setToast('Backend temporarily unavailable')).finally(()=>setLoading(false));
  const login=(event:FormEvent)=>{event.preventDefault();setLoginError('');fetch(`${API}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:loginUsername,password:loginPassword})}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.detail||'Login failed');localStorage.setItem('swasthyanet-token',body.access_token);localStorage.setItem('swasthyanet-user',JSON.stringify(body.user));setToken(body.access_token);setUser(body.user)}).catch(error=>setLoginError(error.message))};
  const logout=()=>{localStorage.removeItem('swasthyanet-token');localStorage.removeItem('swasthyanet-user');setToken('');setUser(null);setData(null);setDetail(null)};
  useEffect(()=>{document.documentElement.dataset.theme=theme; localStorage.setItem('swasthyanet-theme',theme)},[theme]);
  useEffect(()=>{if(token)load()},[token]);
  useEffect(()=>{if(!autoRefresh)return; const id=setInterval(load,8000); return()=>clearInterval(id)},[autoRefresh]);
  useEffect(()=>{if(selected&&token) authFetch(`${API}/api/phcs/${selected}`).then(r=>r.json()).then(setDetail).catch(()=>{})},[selected,data?.tick,token]);
  useEffect(()=>{if(!toast)return; const id=setTimeout(()=>setToast(''),3000); return()=>clearTimeout(id)},[toast]);

  const phcs=useMemo(()=>data?.phcs?.filter((p:any)=>(p.name+' '+p.district).toLowerCase().includes(query.toLowerCase())&&(status==='all'||p.status===status))||[],[data,query,status]);
  const alerts=useMemo(()=>data?.alerts?.filter((a:any)=>alertFilter==='all'||a.severity===alertFilter)||[],[data,alertFilter]);
  if(!token||!user)return <div className="auth-shell"><div className="auth-card"><div className="brandmark auth-mark">S<span>N</span></div><div className="eyebrow teal">SWASTHYANET / SECURE ACCESS</div><h1>Welcome back</h1><p className="auth-subtitle">Sign in to the resilience command center.</p><form onSubmit={login}><label>Role<select value={loginUsername} onChange={e=>{setLoginUsername(e.target.value);setLoginPassword(e.target.value==='state.official'?'State@2026':'Rajapur@2026')}}><option value="state.official">State official — network view</option><option value="rajapur.admin">PHC administrator — Rajapur</option></select></label><label>Username<input value={loginUsername} onChange={e=>setLoginUsername(e.target.value)} autoComplete="username"/></label><label>Password<input value={loginPassword} onChange={e=>setLoginPassword(e.target.value)} type="password" autoComplete="current-password"/></label>{loginError&&<div className="login-error">{loginError}</div>}<button className="primary-btn login-btn" type="submit">Sign in securely <span>→</span></button></form><div className="demo-access"><small>DEMO ACCESS</small><p>State official: <b>state.official</b> / <b>State@2026</b></p><p>PHC admin: <b>rajapur.admin</b> / <b>Rajapur@2026</b></p></div><div className="auth-note">Synthetic hackathon environment · demo accounts only</div></div></div>;
  if(loading||!data)return <div className="loading"><div className="loader-mark">S</div><span>Loading secure PHC network…</span></div>;
  const medicine=detail?.medicines?.[0];
  const curve=(medicine?.forecast?.predicted_quantity||[]).map((quantity:number,day:number)=>({day:`D+${day}`,quantity}));
  const exportSnapshot=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`swasthyanet-snapshot-${data.day}.json`;a.click();URL.revokeObjectURL(url);setToast('Snapshot exported successfully')};
  const simulate=()=>authFetch(`${API}/api/simulate/tick`,{method:'POST'}).then(r=>r.json()).then(setData).then(()=>setToast('Network simulation advanced'));

  return <div className="app">
    {toast&&<div className="toast"><span>✓</span>{toast}</div>}
    <header className="topbar"><div className="brand"><div className="brandmark">S<span>N</span></div><div><div className="eyebrow">NATIONAL HEALTH RESILIENCE</div><h1>Swasthya<span>Net</span></h1></div></div><div className="top-actions"><div className="system-status"><i className="pulse"/> <span>NETWORK ONLINE</span><b>Tick {data.tick}</b></div><div className="role-badge"><span>{user.role==='state_official'?'STATE OFFICIAL':'PHC ADMIN'}</span><b>{user.display_name}</b></div><button className="icon-btn" onClick={()=>setTheme(theme==='light'?'dark':'light')} aria-label="Toggle dark mode"><span className="theme-icon">{theme==='light'?'☾':'☀'}</span><span>{theme==='light'?'Dark mode':'Light mode'}</span></button>{user.role==='state_official'&&<button className="primary-btn" onClick={simulate}><span>↻</span> Simulate update</button>}<button className="logout-btn" onClick={logout}>Sign out</button></div></header>
    <div className="banner"><div className="banner-icon">i</div><div><strong>SYNTHETIC DATASET</strong><span>Demo telemetry is simulated. No patient-level data is used.</span></div><div className="banner-date">Simulation day <b>{data.day}</b></div></div>
    <section className="hero"><div><div className="eyebrow teal">{user.role==='state_official'?'STATE OPERATIONS OVERVIEW':'FACILITY OPERATIONS OVERVIEW'} / 01</div><h2>Resilience command center</h2><p>One operational view for supply, capacity, and local intelligence across the PHC network.</p></div><div className="hero-actions"><button className="secondary-btn" onClick={exportSnapshot}>⇩ Export snapshot</button><label className="switch-label"><span className={`switch ${autoRefresh?'on':''}`} onClick={()=>setAutoRefresh(!autoRefresh)}><i/></span> Auto-refresh <b>{autoRefresh?'ON':'OFF'}</b></label></div></section>
    <section className="kpis">{[['PHC NODES',data.kpis.phcs,'ac','Across network'],['DISTRICTS',data.kpis.districts,'','Coverage area'],['BED UTILIZATION',`${Math.round(data.kpis.occupied/data.kpis.beds*100)}%`, 'warn',`${data.kpis.occupied}/${data.kpis.beds} beds`],['ACTIVE ALERTS',data.kpis.active_alerts,'red','Requires attention'],['CRITICAL',data.kpis.critical_alerts,'red','Priority queue']].map(x=><div className="kpi" key={x[0]}><small>{x[0]}</small><strong className={x[2]}>{x[1]}</strong><span>{x[3]}</span><div className="kpi-line"><i style={{width:`${Math.min(100,Number(String(x[1]).replace('%',''))||data.kpis.phcs*10)}%`}}/></div></div>)}</section>
    <main>
      <section className="panel nodes"><div className="panelhead"><div><small>02 / NETWORK MAP</small><h2>PHC command view</h2></div><div className="legend"><i className="dot green"/>Healthy <i className="dot yellow"/>Watch <i className="dot red"/>Critical</div></div><div className="toolbar"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search PHC or district"/></div><div className="segmented">{['all','green','yellow','red'].map(x=><button className={status===x?'active':''} onClick={()=>setStatus(x)} key={x}>{x==='all'?'All':x}</button>)}</div></div><div className="map">{data.phcs.map((p:any)=><button className={`node ${p.status} ${selected===p.id?'selected':''}`} style={{left:`${18+(p.lon-73.75)*90}%`,top:`${82-(p.lat-17.2)*62}%`}} onClick={()=>setSelected(p.id)} key={p.id}><span>{p.name.replace(' PHC','').replace(' Rural Hospital','')}</span><b>{p.occupancy_pct}%</b></button>)}<div className="route r1"/><div className="route r2"/><div className="maplabel">MAHARASHTRA / DEMO REGION</div><div className="mapscale">⌁ LIVE NODE TELEMETRY</div></div><div className="nodegrid">{phcs.map((p:any)=><button className={`row ${selected===p.id?'active':''}`} onClick={()=>setSelected(p.id)} key={p.id}><i className={`dot ${p.status}`}/><strong>{p.name}</strong><span>{p.district}</span><b>{p.occupancy_pct}% beds · {p.active_alerts} alerts</b><em>›</em></button>)}</div>{phcs.length===0&&<div className="empty">No PHCs match this filter.</div>}</section>
      <section className="panel alerts"><div className="panelhead"><div><small>03 / EARLY WARNING SYSTEM</small><h2>Live alert feed</h2></div><span className="count">{alerts.length} events</span></div><div className="alerttabs">{['all','critical','warning'].map(x=><button className={alertFilter===x?'active':''} onClick={()=>setAlertFilter(x)} key={x}>{x} <b>{x==='all'?data.alerts.length:data.alerts.filter((a:any)=>a.severity===x).length}</b></button>)}</div>{alerts.slice(0,8).map((a:any,i:number)=><div className="alert" key={i}><i className={`dot ${a.severity==='critical'?'red':'yellow'}`}/><div><strong>{a.title}</strong><p>{a.message}</p></div><small>{i<2?'NOW':`${i+1}m ago`}</small></div>)}{alerts.length===0&&<div className="empty">No alerts in this filter.</div>}</section>
      <section className="panel forecast"><div className="panelhead"><div><small>04 / EXPLAINABLE FORECAST</small><h2>{detail?.phc?.name || 'PHC'} inventory trajectory</h2></div><div className="method"><span className="status-chip">● MODEL ACTIVE</span> Weighted moving average · 7-day window</div></div><div className="forecastmeta"><div><small>SELECTED SKU</small><strong>{medicine?.medicine_id || 'Loading'}</strong><span>Essential medicine</span></div><div><small>EST. DAILY USE</small><strong>{medicine?.forecast?.predicted_daily_use || '—'} <i>units</i></strong><span>Recent 7-day signal</span></div><div><small>STOCKOUT ETA</small><strong className="redtext">{medicine?.forecast?.days_until_stockout || '—'} <i>days</i></strong><span>Based on current stock</span></div><div><small>CONFIDENCE</small><strong>{medicine?.forecast?.confidence ? `${Math.round(medicine.forecast.confidence*100)}%`:'—'}</strong><span>History-backed</span></div></div><div className="chart"><ResponsiveContainer width="100%" height={245}><AreaChart data={curve}><defs><linearGradient id="stockFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0e9b7d" stopOpacity={.28}/><stop offset="100%" stopColor="#0e9b7d" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="var(--grid)"/><XAxis dataKey="day" tick={{fill:'var(--muted)',fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:'var(--muted)',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--border)',borderRadius:8,color:'var(--text)'}}/><Area type="monotone" dataKey="quantity" stroke="#0e9b7d" fill="url(#stockFill)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></section>
      <section className="panel recommendations"><div className="panelhead"><div><small>05 / REDISTRIBUTION ENGINE</small><h2>Recommended transfers</h2></div><span className="count">{data.recommendations.length} matches</span></div>{data.recommendations.slice(0,4).map((r:any,i:number)=><div className="transfer" key={i}><div className="transferpath"><span className="transfer-icon">↗</span><b>{r.source_name}</b><span className="transfer-arrow">→</span><b>{r.destination_name}</b><span className={`priority ${r.priority}`}>{r.priority}</span></div><div className="transferinfo"><span className="pill">{r.medicine_id}</span><strong>{r.quantity} units</strong><span>{r.distance_km} km route</span></div><p>{r.reason}</p></div>)}{data.recommendations.length===0&&<div className="empty">No redistribution actions needed.</div>}</section>
      <section className="panel federation"><div className="panelhead"><div><small>06 / PRIVACY-PRESERVING AGGREGATION</small><h2>Federated learning boundary</h2></div><span className="secure">● RAW DATA STAYS LOCAL</span></div><div className="flow"><div className="flowbox"><div className="flow-number">{data.federated.nodes}</div><strong>PHC local nodes</strong><small>Inventory · attendance<br/>patient events</small></div><div className="arrow">→<small>aggregate<br/>only</small></div><div className="flowbox central"><div className="flow-number">◎</div><strong>State aggregator</strong><small>Weighted occupancy<br/>& model metrics</small></div><div className="arrow">→</div><div className="flowbox"><div className="flow-number">∞</div><strong>Planning insight</strong><small>Resilience actions<br/>without raw records</small></div></div><div className="privacy"><span>⌁</span>{data.federated.privacy_boundary}</div></section>
    </main><footer><span><b>SWASTHYANET</b> / MVP 0.2</span><span>Federated intelligence for resilient public health operations</span><span>Last sync · {data.day} · Tick {data.tick}</span></footer>
  </div>
}
createRoot(document.getElementById('root')!).render(<App/>);
