import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid} from 'recharts';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';

type Dash = any;
function App(){
 const [data,setData]=useState<Dash|null>(null); const [selected,setSelected]=useState('phc-rajapur'); const [detail,setDetail]=useState<any>(null); const [loading,setLoading]=useState(true);
 const load=()=>fetch(`${API}/api/dashboard`).then(r=>r.json()).then(setData).finally(()=>setLoading(false));
 useEffect(()=>{load(); const id=setInterval(load,8000); return()=>clearInterval(id)},[]);
 useEffect(()=>{if(selected) fetch(`${API}/api/phcs/${selected}`).then(r=>r.json()).then(setDetail)},[selected,data?.tick]);
 if(loading||!data)return <div className="loading">Loading synthetic PHC network…</div>;
 const medicine=detail?.medicines?.[0]; const curve=(medicine?.forecast?.predicted_quantity||[]).map((quantity:number,day:number)=>({day:`D+${day}`,quantity}));
 return <div className="app"><header><div><div className="eyebrow">NATIONAL HEALTH RESILIENCE / FEDERATED NODE NETWORK</div><h1>Swasthya<span>Net</span></h1><p className="muted">Operational visibility for India’s Primary Health Centres</p></div><div className="live"><i/> LIVE SIMULATION <b>Tick {data.tick}</b><button onClick={()=>{fetch(`${API}/api/simulate/tick`,{method:'POST'}).then(r=>r.json()).then(setData)}}>Simulate update</button></div></header>
 <div className="banner"><strong>SYNTHETIC DATASET</strong><span>All PHC, inventory, staffing, and forecast values are simulated for hackathon demonstration. No patient-level data is used.</span><span className="date">Simulation day {data.day}</span></div>
 <section className="kpis">{[['PHC NODES',data.kpis.phcs,'ac'],['DISTRICTS',data.kpis.districts,''],['BED OCCUPANCY',`${data.kpis.occupied}/${data.kpis.beds}`, 'warn'],['ACTIVE ALERTS',data.kpis.active_alerts,'red'],['CRITICAL',data.kpis.critical_alerts,'red']].map(x=><div className="kpi" key={x[0]}><small>{x[0]}</small><strong className={x[2]}>{x[1]}</strong><span>Network telemetry</span></div>)}</section>
 <main><section className="panel nodes"><div className="panelhead"><div><small>01 / NETWORK MAP</small><h2>PHC command view</h2></div><span className="legend"><i className="dot green"/>Healthy <i className="dot yellow"/>Watch <i className="dot red"/>Critical</span></div><div className="map">{data.phcs.map((p:any)=><button className={`node ${p.status} ${selected===p.id?'selected':''}`} style={{left:`${18+(p.lon-73.75)*90}%`,top:`${82-(p.lat-17.2)*62}%`}} onClick={()=>setSelected(p.id)} key={p.id}><span>{p.name.replace(' PHC','')}</span><b>{p.occupancy_pct}%</b></button>)}<div className="route r1"/><div className="route r2"/><div className="maplabel">MAHARASHTRA / DEMO REGION</div></div><div className="nodegrid">{data.phcs.map((p:any)=><button className={`row ${selected===p.id?'active':''}`} onClick={()=>setSelected(p.id)} key={p.id}><i className={`dot ${p.status}`}/><strong>{p.name}</strong><span>{p.district}</span><b>{p.occupancy_pct}% beds</b></button>)}</div></section>
 <section className="panel alerts"><div className="panelhead"><div><small>02 / EARLY WARNING SYSTEM</small><h2>Live alert feed</h2></div><span className="count">{data.alerts.length} events</span></div>{data.alerts.slice(0,7).map((a:any,i:number)=><div className="alert" key={i}><i className={`dot ${a.severity==='critical'?'red':'yellow'}`}/><div><strong>{a.title}</strong><p>{a.message}</p></div><small>{i<2?'NOW':'2m ago'}</small></div>)}</section>
 <section className="panel forecast"><div className="panelhead"><div><small>03 / EXPLAINABLE FORECAST</small><h2>{detail?.phc?.name || 'PHC'} inventory trajectory</h2></div><span className="method">Weighted moving average · 7-day window</span></div><div className="forecastmeta"><div><small>SELECTED SKU</small><strong>{medicine?.medicine_id || 'Loading'}</strong></div><div><small>EST. DAILY USE</small><strong>{medicine?.forecast?.predicted_daily_use || '—'} units</strong></div><div><small>STOCKOUT ETA</small><strong className="redtext">{medicine?.forecast?.days_until_stockout || '—'} days</strong></div><div><small>CONFIDENCE</small><strong>{medicine?.forecast?.confidence ? `${Math.round(medicine.forecast.confidence*100)}%`:'—'}</strong></div></div><div className="chart"><ResponsiveContainer width="100%" height={230}><LineChart data={curve}><CartesianGrid strokeDasharray="3 3" stroke="#d9e3df"/><XAxis dataKey="day"/><YAxis/><Tooltip/><Line type="monotone" dataKey="quantity" stroke="#0e8f75" strokeWidth={3} dot={{r:3}}/></LineChart></ResponsiveContainer></div></section>
 <section className="panel recommendations"><div className="panelhead"><div><small>04 / REDISTRIBUTION ENGINE</small><h2>Recommended transfers</h2></div><span className="count">{data.recommendations.length} matches</span></div>{data.recommendations.slice(0,4).map((r:any,i:number)=><div className="transfer" key={i}><div className="transferpath"><b>{r.source_name}</b><span>→</span><b>{r.destination_name}</b></div><div className="transferinfo"><span className="pill">{r.medicine_id}</span><strong>{r.quantity} units</strong><span>{r.distance_km} km · {r.priority} priority</span></div><p>{r.reason}</p></div>)}</section>
 <section className="panel federation"><div className="panelhead"><div><small>05 / PRIVACY-PRESERVING AGGREGATION</small><h2>Federated learning boundary</h2></div><span className="secure">● RAW DATA STAYS LOCAL</span></div><div className="flow"><div className="flowbox"><strong>{data.federated.nodes}</strong><span>PHC local nodes</span><small>Inventory · attendance<br/>patient events</small></div><div className="arrow">→<small>aggregated<br/>updates only</small></div><div className="flowbox central"><strong>STATE</strong><span>Federated aggregator</span><small>Weighted occupancy<br/>& model metrics</small></div><div className="arrow">→</div><div className="flowbox"><strong>∞</strong><span>Planning insight</span><small>Resilience actions<br/>without raw records</small></div></div><p className="privacy">{data.federated.privacy_boundary}</p></section>
 </main><footer><span>SWASTHYANET / MVP 0.1</span><span>Designed for resilient public health operations · synthetic demo</span></footer></div>
}
createRoot(document.getElementById('root')!).render(<App/>);
